const biology = [
    { question: "What is the primary function of the mitochondria in a cell?", answer: "Energy production", type: "multiple choice", choices: ["Protein synthesis", "Cellular respiration", "Energy production", "DNA replication"] },
    { question: "What is the smallest unit of life?", answer: "Cell", type: "multiple choice", choices: ["Organism", "Tissue", "Cell", "Organ"] },
    { question: "Which organelle is responsible for protein synthesis?", answer: "Ribosomes", type: "multiple choice", choices: ["Golgi apparatus", "Mitochondria", "Lysosomes", "Ribosomes"] },
    { question: "What is the function of the nucleus in a cell?", answer: "Contains DNA and controls cell activities", type: "multiple choice", choices: ["Produces energy", "Stores water", "Contains DNA and controls cell activities", "Breaks down waste"] },
    { question: "What is the process by which cells break down glucose to release energy?", answer: "Cellular respiration", type: "multiple choice", choices: ["Photosynthesis", "Fermentation", "Cellular respiration", "Mitosis"] },
    { question: "Which molecule carries genetic information in cells?", answer: "DNA", type: "multiple choice", choices: ["RNA", "Protein", "Carbohydrate", "DNA"] },
    { question: "What is the function of the chloroplast in a plant cell?", answer: "Photosynthesis", type: "multiple choice", choices: ["Cellular respiration", "Protein synthesis", "Storage of nutrients", "Photosynthesis"] },
    { question: "Which process allows cells to divide and reproduce?", answer: "Mitosis", type: "multiple choice", choices: ["Meiosis", "Fertilization", "Photosynthesis", "Mitosis"] },
    { question: "What is the basic unit of DNA called?", answer: "Nucleotide", type: "multiple choice", choices: ["Amino acid", "Lipid", "Carbohydrate", "Nucleotide"] },
    { question: "Which organelle is responsible for detoxifying harmful substances in a cell?", answer: "Smooth endoplasmic reticulum", type: "multiple choice", choices: ["Golgi apparatus", "Rough endoplasmic reticulum", "Nucleus", "Smooth endoplasmic reticulum"] },
    { question: "Which type of cell division is involved in the production of gametes?", answer: "Meiosis", type: "multiple choice", choices: ["Mitosis", "Fertilization", "Photosynthesis", "Meiosis"] },
    { question: "What is the function of the cell membrane?", answer: "Regulates the passage of substances in and out of the cell", type: "multiple choice", choices: ["Stores genetic information", "Produces energy", "Breaks down waste", "Regulates the passage of substances in and out of the cell"] },
    { question: "What is the process by which plants convert sunlight into chemical energy?", answer: "Photosynthesis", type: "multiple choice", choices: ["Cellular respiration", "Fermentation", "Photosynthesis", "Mitosis"] },
    { question: "Which type of biomolecule includes enzymes, antibodies, and hormones?", answer: "Proteins", type: "multiple choice", choices: ["Lipids", "Carbohydrates", "Nucleic acids", "Proteins"] },
    { question: "What is the main function of the ribosomes in a cell?", answer: "Protein synthesis", type: "multiple choice", choices: ["Energy production", "Cellular respiration", "DNA replication", "Protein synthesis"] },
    { question: "Which type of cell division results in the formation of two identical daughter cells?", answer: "Mitosis", type: "multiple choice", choices: ["Meiosis", "Fertilization", "Photosynthesis", "Mitosis"] },
    { question: "What is the role of enzymes in biological reactions?", answer: "Catalyze chemical reactions", type: "multiple choice", choices: ["Store genetic information", "Produce energy", "Break down waste", "Catalyze chemical reactions"] },
    { question: "What is the function of the Golgi apparatus in a cell?", answer: "Modifies, sorts, and packages proteins", type: "multiple choice", choices: ["Energy production", "Cellular respiration", "DNA replication", "Modifies, sorts, and packages proteins"] },
    { question: "Which organelle contains digestive enzymes for breaking down waste materials?", answer: "Lysosomes", type: "multiple choice", choices: ["Golgi apparatus", "Mitochondria", "Endoplasmic reticulum", "Lysosomes"] },
    { question: "What is the process by which cells capture and utilize energy from sunlight?", answer: "Photosynthesis", type: "multiple choice", choices: ["Cellular respiration", "Fermentation", "Photosynthesis", "Mitosis"] },
    { question: "Which molecule is the universal energy currency of cells?", answer: "Adenosine triphosphate (ATP)", type: "multiple choice", choices: ["Glucose", "Lipid", "Nucleotide", "Adenosine triphosphate (ATP)"] },
    { question: "What is the function of the rough endoplasmic reticulum in a cell?", answer: "Protein synthesis and processing", type: "multiple choice", choices: ["Energy production", "Cellular respiration", "DNA replication", "Protein synthesis and processing"] },
    { question: "Which process allows for the exchange of gases in the lungs?", answer: "Respiration", type: "multiple choice", choices: ["Digestion", "Circulation", "Excretion", "Respiration"] },
    { question: "What is the structure that carries genetic information from the nucleus to the ribosomes?", answer: "Messenger RNA (mRNA)", type: "multiple choice", choices: ["Transfer RNA (tRNA)", "Ribosomal RNA (rRNA)", "Messenger RNA (mRNA)", "MicroRNA (miRNA)"] },
    { question: "What is the function of the centrioles in animal cells?", answer: "Organize spindle fibers during cell division", type: "multiple choice", choices: ["Produce energy", "Store genetic information", "Break down waste", "Organize spindle fibers during cell division"] },
    { question: "Which process allows for the movement of substances against their concentration gradient?", answer: "Active transport", type: "multiple choice", choices: ["Diffusion", "Osmosis", "Facilitated diffusion", "Active transport"] },
    { question: "What is the function of the cytoskeleton in a cell?", answer: "Provides structure and facilitates cell movement", type: "multiple choice", choices: ["Energy production", "DNA replication", "Protein synthesis", "Provides structure and facilitates cell movement"] },
    { question: "Which process involves the exchange of genetic material between homologous chromosomes?", answer: "Crossing over", type: "multiple choice", choices: ["Transcription", "Translation", "Crossing over", "Mutation"] },
    { question: "What is the function of the cell wall in plant cells?", answer: "Provides support and protection", type: "multiple choice", choices: ["Energy production", "DNA replication", "Protein synthesis", "Provides support and protection"] },
    { question: "Which process involves the replication of DNA?", answer: "DNA replication", type: "multiple choice", choices: ["Transcription", "Translation", "DNA replication", "Mutation"] },
    { question: "What is the function of the stomata in plant leaves?", answer: "Regulate gas exchange and water loss", type: "multiple choice", choices: ["Produce energy", "Store genetic information", "Break down waste", "Regulate gas exchange and water loss"] },
    { question: "Which type of cell division results in the formation of four non-identical daughter cells?", answer: "Meiosis", type: "multiple choice", choices: ["Mitosis", "Fertilization", "Photosynthesis", "Meiosis"] },
    { question: "What is the role of tRNA in protein synthesis?", answer: "Delivers amino acids to the ribosomes", type: "multiple choice", choices: ["Carries genetic information", "Produces energy", "Breaks down waste", "Delivers amino acids to the ribosomes"] },
    { question: "Which process involves the movement of water across a semipermeable membrane?", answer: "Osmosis", type: "multiple choice", choices: ["Diffusion", "Active transport", "Facilitated diffusion", "Osmosis"] },
    { question: "What is the function of the nucleolus in a cell?", answer: "Produces ribosomes", type: "multiple choice", choices: ["Produces energy", "Stores genetic information", "Breaks down waste", "Produces ribosomes"] },
    { question: "Which process involves the conversion of nitrogen gas into a usable form by bacteria?", answer: "Nitrogen fixation", type: "multiple choice", choices: ["Photosynthesis", "Fermentation", "Nitrogen fixation", "Mitosis"] },
    { question: "What is the function of the cilia in cells?", answer: "Facilitate movement", type: "multiple choice", choices: ["Energy production", "Protein synthesis", "Storage of nutrients", "Facilitate movement"] },
    { question: "Which process involves the production of gametes?", answer: "Gametogenesis", type: "multiple choice", choices: ["Embryogenesis", "Fertilization", "Photosynthesis", "Gametogenesis"] },
    { question: "What is the function of the flagella in cells?", answer: "Facilitate cell movement", type: "multiple choice", choices: ["Store genetic information", "Produce energy", "Break down waste", "Facilitate cell movement"] },
    { question: "Which process involves the production of ATP in the mitochondria?", answer: "Cellular respiration", type: "multiple choice", choices: ["Photosynthesis", "Fermentation", "Cellular respiration", "Mitosis"] },
    { question: "What is the function of the spindle fibers during cell division?", answer: "Separate chromosomes", type: "multiple choice", choices: ["Produce energy", "Store genetic information", "Break down waste", "Separate chromosomes"] },
    { question: "Which process involves the movement of substances from an area of higher concentration to an area of lower concentration?", answer: "Diffusion", type: "multiple choice", choices: ["Osmosis", "Active transport", "Facilitated diffusion", "Diffusion"] },
    { question: "What is the function of the peroxisomes in a cell?", answer: "Break down fatty acids and detoxify harmful substances", type: "multiple choice", choices: ["Energy production", "Protein synthesis", "DNA replication", "Break down fatty acids and detoxify harmful substances"] },
    { question: "Which process involves the formation of a new individual from a single parent?", answer: "Asexual reproduction", type: "multiple choice", choices: ["Sexual reproduction", "Fertilization", "Photosynthesis", "Asexual reproduction"] },
    { question: "What is the function of the endoplasmic reticulum in a cell?", answer: "Facilitates protein synthesis and lipid metabolism", type: "multiple choice", choices: ["Energy production", "Cellular respiration", "DNA replication", "Facilitates protein synthesis and lipid metabolism"] },
    { question: "Which type of biomolecule stores and transmits genetic information?", answer: "Nucleic acids", type: "multiple choice", choices: ["Lipids", "Carbohydrates", "Proteins", "Nucleic acids"] },
    { question: "What is the process by which a cell engulfs and takes in solid particles?", answer: "Phagocytosis", type: "multiple choice", choices: ["Exocytosis", "Pinocytosis", "Endocytosis", "Phagocytosis"] },
    { question: "What is the function of the vacuole in a plant cell?", answer: "Storage of water and nutrients", type: "multiple choice", choices: ["Energy production", "Protein synthesis", "Break down waste", "Storage of water and nutrients"] },
    { question: "Which process involves the conversion of light energy into chemical energy?", answer: "Photosynthesis", type: "multiple choice", choices: ["Cellular respiration", "Fermentation", "Photosynthesis", "Mitosis"] },
    { question: "What is the function of the nucleic acids in cells?", answer: "Store and transmit genetic information", type: "multiple choice", choices: ["Produce energy", "Catalyze chemical reactions", "Facilitate cell movement", "Store and transmit genetic information"] }
]

const AP_biology = [
    { question: "What is the primary function of DNA?", answer: "Stores and transmits genetic information", type: "multiple choice", choices: ["Produces energy for the cell", "Regulates gene expression", "Facilitates cell communication", "Stores and transmits genetic information"] },
    { question: "Which organelle is responsible for protein synthesis?", answer: "Ribosomes", type: "multiple choice", choices: ["Mitochondria", "Golgi apparatus", "Endoplasmic reticulum", "Ribosomes"] },
    { question: "What is the energy currency of the cell?", answer: "ATP", type: "multiple choice", choices: ["DNA", "RNA", "ATP", "GTP"] },
    { question: "Which process involves the production of gametes?", answer: "Meiosis", type: "multiple choice", choices: ["Mitosis", "Fertilization", "Transcription", "Meiosis"] },
    { question: "What is the function of enzymes in biological reactions?", answer: "Catalyze chemical reactions", type: "multiple choice", choices: ["Store genetic information", "Produce energy", "Facilitate cell movement", "Catalyze chemical reactions"] },
    { question: "Which molecule carries amino acids to the ribosomes during protein synthesis?", answer: "tRNA", type: "multiple choice", choices: ["mRNA", "rRNA", "DNA", "tRNA"] },
    { question: "What is the role of the Golgi apparatus in the cell?", answer: "Modifies, sorts, and packages proteins", type: "multiple choice", choices: ["Produces energy", "Stores genetic information", "Breaks down waste", "Modifies, sorts, and packages proteins"] },
    { question: "Which process involves the conversion of light energy into chemical energy in plants?", answer: "Photosynthesis", type: "multiple choice", choices: ["Cellular respiration", "Fermentation", "Photosynthesis", "Mitosis"] },
    { question: "What is the function of the cell membrane?", answer: "Regulates the movement of substances in and out of the cell", type: "multiple choice", choices: ["Stores water and nutrients", "Produces energy", "Breaks down waste", "Regulates the movement of substances in and out of the cell"] },
    { question: "Which macromolecule is responsible for storing genetic information?", answer: "DNA", type: "multiple choice", choices: ["Proteins", "Carbohydrates", "Lipids", "DNA"] },
    { question: "What is the function of the mitochondria in the cell?", answer: "Produces energy through cellular respiration", type: "multiple choice", choices: ["Synthesizes proteins", "Stores genetic information", "Breaks down waste", "Produces energy through cellular respiration"] },
    { question: "Which process involves the conversion of glucose into ATP?", answer: "Cellular respiration", type: "multiple choice", choices: ["Photosynthesis", "Fermentation", "Cellular respiration", "Mitosis"] },
    { question: "What is the process by which mRNA is synthesized from a DNA template?", answer: "Transcription", type: "multiple choice", choices: ["Translation", "Replication", "Translocation", "Transcription"] },
    { question: "What is the function of the chloroplasts in plant cells?", answer: "Carry out photosynthesis", type: "multiple choice", choices: ["Produce energy", "Synthesize proteins", "Store genetic information", "Carry out photosynthesis"] },
    { question: "Which process involves the separation of homologous chromosomes?", answer: "Meiosis", type: "multiple choice", choices: ["Mitosis", "Fertilization", "Transcription", "Meiosis"] },
    { question: "What is the role of the nucleus in a eukaryotic cell?", answer: "Stores genetic information", type: "multiple choice", choices: ["Produces energy", "Synthesizes proteins", "Breaks down waste", "Stores genetic information"] },
    { question: "Which molecule is responsible for carrying genetic information from the nucleus to the ribosomes?", answer: "mRNA", type: "multiple choice", choices: ["tRNA", "rRNA", "DNA", "mRNA"] },
    { question: "What is the function of the lysosomes in a cell?", answer: "Break down cellular waste and debris", type: "multiple choice", choices: ["Produce energy", "Store genetic information", "Facilitate cell movement", "Break down cellular waste and debris"] },
    { question: "Which process involves the formation of a new individual through the union of gametes?", answer: "Fertilization", type: "multiple choice", choices: ["Recombination", "Meiosis", "Photosynthesis", "Fertilization"] },
    { question: "What is the function of the cytoskeleton in the cell?", answer: "Provides structural support and facilitates cell movement", type: "multiple choice", choices: ["Stores water and nutrients", "Synthesizes proteins", "Breaks down waste", "Provides structural support and facilitates cell movement"] },
    { question: "Which process involves the synthesis of proteins based on the sequence of codons in mRNA?", answer: "Translation", type: "multiple choice", choices: ["Transcription", "Replication", "Translocation", "Translation"] },
    { question: "What is the function of the centrioles in animal cells?", answer: "Assist in cell division", type: "multiple choice", choices: ["Produce energy", "Store genetic information", "Break down waste", "Assist in cell division"] },
    { question: "Which process involves the replication of DNA?", answer: "DNA replication", type: "multiple choice", choices: ["Protein synthesis", "Cellular respiration", "Photosynthesis", "DNA replication"] },
    { question: "What is the function of the ribosomes in a cell?", answer: "Protein synthesis", type: "multiple choice", choices: ["Energy production", "DNA replication", "Facilitate cell movement", "Protein synthesis"] },
    { question: "Which molecule is responsible for carrying amino acids to the ribosomes during protein synthesis?", answer: "tRNA", type: "multiple choice", choices: ["mRNA", "rRNA", "DNA", "tRNA"] },
    { question: "What is the function of the Golgi apparatus in a cell?", answer: "Modifies, sorts, and packages proteins", type: "multiple choice", choices: ["Produces energy", "Stores genetic information", "Breaks down waste", "Modifies, sorts, and packages proteins"] },
    { question: "Which process involves the conversion of light energy into chemical energy in plants?", answer: "Photosynthesis", type: "multiple choice", choices: ["Cellular respiration", "Fermentation", "Photosynthesis", "Mitosis"] },
    { question: "What is the function of the cell membrane?", answer: "Regulates the movement of substances in and out of the cell", type: "multiple choice", choices: ["Stores water and nutrients", "Produces energy", "Breaks down waste", "Regulates the movement of substances in and out of the cell"] },
    { question: "Which macromolecule is responsible for storing genetic information?", answer: "DNA", type: "multiple choice", choices: ["Proteins", "Carbohydrates", "Lipids", "DNA"] },
    { question: "What is the function of the mitochondria in a cell?", answer: "Produces energy through cellular respiration", type: "multiple choice", choices: ["Synthesizes proteins", "Stores genetic information", "Breaks down waste", "Produces energy through cellular respiration"] },
    { question: "Which process involves the conversion of glucose into ATP?", answer: "Cellular respiration", type: "multiple choice", choices: ["Photosynthesis", "Fermentation", "Cellular respiration", "Mitosis"] },
    { question: "What is the process by which mRNA is synthesized from a DNA template?", answer: "Transcription", type: "multiple choice", choices: ["Translation", "Replication", "Translocation", "Transcription"] },
    { question: "What is the function of the chloroplasts in plant cells?", answer: "Carry out photosynthesis", type: "multiple choice", choices: ["Produce energy", "Store genetic information", "Break down waste", "Carry out photosynthesis"] },
    { question: "Which process involves the separation of homologous chromosomes?", answer: "Meiosis", type: "multiple choice", choices: ["Mitosis", "Fertilization", "Transcription", "Meiosis"] },
    { question: "What is the role of the nucleus in a eukaryotic cell?", answer: "Stores genetic information", type: "multiple choice", choices: ["Produces energy", "Synthesizes proteins", "Breaks down waste", "Stores genetic information"] },
    { question: "Which molecule is responsible for carrying genetic information from the nucleus to the ribosomes?", answer: "mRNA", type: "multiple choice", choices: ["tRNA", "rRNA", "DNA", "mRNA"] },
    { question: "What is the function of the lysosomes in a cell?", answer: "Break down cellular waste and debris", type: "multiple choice", choices: ["Produce energy", "Store genetic information", "Facilitate cell movement", "Break down cellular waste and debris"] },
    { question: "Which process involves the formation of a new individual through the union of gametes?", answer: "Fertilization", type: "multiple choice", choices: ["Recombination", "Meiosis", "Photosynthesis", "Fertilization"] },
    { question: "What is the function of the cytoskeleton in the cell?", answer: "Provides structural support and facilitates cell movement", type: "multiple choice", choices: ["Stores water and nutrients", "Synthesizes proteins", "Breaks down waste", "Provides structural support and facilitates cell movement"] },
    { question: "Which process involves the synthesis of proteins based on the sequence of codons in mRNA?", answer: "Translation", type: "multiple choice", choices: ["Transcription", "Replication", "Translocation", "Translation"] },
    { question: "What is the function of the centrioles in animal cells?", answer: "Assist in cell division", type: "multiple choice", choices: ["Produce energy", "Store genetic information", "Break down waste", "Assist in cell division"] },
    { question: "Which process involves the replication of DNA?", answer: "DNA replication", type: "multiple choice", choices: ["Protein synthesis", "Cellular respiration", "Photosynthesis", "DNA replication"] },
    { question: "What is the function of the ribosomes in a cell?", answer: "Protein synthesis", type: "multiple choice", choices: ["Energy production", "DNA replication", "Facilitate cell movement", "Protein synthesis"] },
    { question: "Which molecule is responsible for carrying amino acids to the ribosomes during protein synthesis?", answer: "tRNA", type: "multiple choice", choices: ["mRNA", "rRNA", "DNA", "tRNA"] },
    { question: "What is the function of the Golgi apparatus in a cell?", answer: "Modifies, sorts, and packages proteins", type: "multiple choice", choices: ["Produces energy", "Stores genetic information", "Breaks down waste", "Modifies, sorts, and packages proteins"] },
    { question: "Which process involves the conversion of light energy into chemical energy in plants?", answer: "Photosynthesis", type: "multiple choice", choices: ["Cellular respiration", "Fermentation", "Photosynthesis", "Mitosis"] },
    { question: "What is the function of the cell membrane?", answer: "Regulates the movement of substances in and out of the cell", type: "multiple choice", choices: ["Stores water and nutrients", "Produces energy", "Breaks down waste", "Regulates the movement of substances in and out of the cell"] },
    { question: "Which macromolecule is responsible for storing genetic information?", answer: "DNA", type: "multiple choice", choices: ["Proteins", "Carbohydrates", "Lipids", "DNA"] },
    { question: "What is the function of the mitochondria in a cell?", answer: "Produces energy through cellular respiration", type: "multiple choice", choices: ["Synthesizes proteins", "Stores genetic information", "Breaks down waste", "Produces energy through cellular respiration"] },
    { question: "Which process involves the conversion of glucose into ATP?", answer: "Cellular respiration", type: "multiple choice", choices: ["Photosynthesis", "Fermentation", "Cellular respiration", "Mitosis"] }
]

const chemistry = [
    { question: "What is the atomic number of carbon?", answer: "6", type: "multiple choice", choices: ["4", "6", "8", "12"] },
    { question: "What is the chemical symbol for gold?", answer: "Au", type: "multiple choice", choices: ["Ag", "Fe", "Au", "Cu"] },
    { question: "What is the pH value of a neutral solution?", answer: "7", type: "multiple choice", choices: ["1", "4", "7", "10"] },
    { question: "What is the formula for methane?", answer: "CH4", type: "multiple choice", choices: ["CO2", "H2O", "CH4", "C6H12O6"] },
    { question: "Which subatomic particle has a negative charge?", answer: "Electron", type: "multiple choice", choices: ["Proton", "Neutron", "Electron", "Nucleus"] },
    { question: "What is the process called when a gas changes directly into a solid?", answer: "Deposition", type: "multiple choice", choices: ["Sublimation", "Evaporation", "Condensation", "Deposition"] },
    { question: "What is the molar mass of water (H2O)?", answer: "18 g/mol", type: "multiple choice", choices: ["12 g/mol", "16 g/mol", "18 g/mol", "22 g/mol"] },
    { question: "What is the chemical formula for sulfuric acid?", answer: "H2SO4", type: "multiple choice", choices: ["HCl", "HNO3", "H2SO4", "NaOH"] },
    { question: "Which gas is produced during photosynthesis?", answer: "Oxygen", type: "multiple choice", choices: ["Carbon dioxide", "Oxygen", "Methane", "Nitrogen"] },
    { question: "What is the process called when a solid changes directly into a gas?", answer: "Sublimation", type: "multiple choice", choices: ["Evaporation", "Condensation", "Sublimation", "Deposition"] },
    { question: "What is the chemical formula for glucose?", answer: "C6H12O6", type: "multiple choice", choices: ["H2O", "CH4", "C6H12O6", "CO2"] },
    { question: "What is the SI unit for measuring temperature?", answer: "Kelvin", type: "multiple choice", choices: ["Celsius", "Fahrenheit", "Kelvin", "Rankine"] },
    { question: "What is the law of conservation of mass?", answer: "Mass is neither created nor destroyed in a chemical reaction", type: "multiple choice", choices: ["Mass increases in a chemical reaction", "Mass decreases in a chemical reaction", "Mass is zero in a chemical reaction", "Mass is neither created nor destroyed in a chemical reaction"] },
    { question: "What is the chemical symbol for sodium?", answer: "Na", type: "multiple choice", choices: ["Ni", "S", "Na", "Mg"] },
    { question: "What is the formula for calculating density?", answer: "Density = Mass / Volume", type: "multiple choice", choices: ["Density = Mass * Volume", "Density = Mass - Volume", "Density = Mass + Volume", "Density = Mass / Volume"] },
    { question: "Which element is a noble gas?", answer: "Helium", type: "multiple choice", choices: ["Oxygen", "Nitrogen", "Hydrogen", "Helium"] },
    { question: "What is the SI unit for measuring pressure?", answer: "Pascal", type: "multiple choice", choices: ["Newton", "Joule", "Watt", "Pascal"] },
    { question: "What is the chemical formula for hydrochloric acid?", answer: "HCl", type: "multiple choice", choices: ["H2SO4", "HNO3", "HCl", "NaOH"] },
    { question: "What is the process called when a gas changes into a liquid?", answer: "Condensation", type: "multiple choice", choices: ["Sublimation", "Evaporation", "Condensation", "Deposition"] },
    { question: "What is the atomic number of oxygen?", answer: "8", type: "multiple choice", choices: ["4", "6", "8", "12"] },
    { question: "Which is the lightest element?", answer: "Hydrogen", type: "multiple choice", choices: ["Oxygen", "Nitrogen", "Carbon", "Hydrogen"] },
    { question: "What is the chemical formula for carbon dioxide?", answer: "CO2", type: "multiple choice", choices: ["H2O", "CH4", "CO2", "C6H12O6"] },
    { question: "What is the pH value of an acidic solution?", answer: "Less than 7", type: "multiple choice", choices: ["Less than 1", "Less than 4", "Less than 7", "Less than 10"] },
    { question: "What is the SI unit for measuring energy?", answer: "Joule", type: "multiple choice", choices: ["Newton", "Watt", "Pascal", "Joule"] },
    { question: "What is the chemical symbol for iron?", answer: "Fe", type: "multiple choice", choices: ["Ag", "Fe", "Au", "Cu"] },
    { question: "What is the process called when a liquid changes into a gas?", answer: "Evaporation", type: "multiple choice", choices: ["Sublimation", "Evaporation", "Condensation", "Deposition"] },
    { question: "What is the molar mass of carbon dioxide (CO2)?", answer: "44 g/mol", type: "multiple choice", choices: ["12 g/mol", "16 g/mol", "28 g/mol", "44 g/mol"] },
    { question: "Which gas is responsible for the greenhouse effect?", answer: "Carbon dioxide", type: "multiple choice", choices: ["Oxygen", "Carbon dioxide", "Methane", "Nitrogen"] },
    { question: "What is the process called when a liquid changes into a solid?", answer: "Solidification", type: "multiple choice", choices: ["Evaporation", "Condensation", "Solidification", "Melting"] },
    { question: "What is the chemical formula for water?", answer: "H2O", type: "multiple choice", choices: ["CO2", "H2O", "CH4", "NaCl"] },
    { question: "What is the SI unit for measuring mass?", answer: "Kilogram", type: "multiple choice", choices: ["Gram", "Pound", "Newton", "Kilogram"] },
    { question: "Which subatomic particle is located in the nucleus of an atom?", answer: "Proton", type: "multiple choice", choices: ["Electron", "Neutron", "Proton", "Atom"] },
    { question: "What is the chemical symbol for helium?", answer: "He", type: "multiple choice", choices: ["Ne", "Ar", "He", "Kr"] },
    { question: "What is the formula for calculating speed?", answer: "Speed = Distance / Time", type: "multiple choice", choices: ["Speed = Distance * Time", "Speed = Distance - Time", "Speed = Distance + Time", "Speed = Distance / Time"] },
    { question: "What is the pH value of a basic solution?", answer: "Greater than 7", type: "multiple choice", choices: ["Greater than 1", "Greater than 4", "Greater than 7", "Greater than 10"] },
    { question: "What is the atomic number of hydrogen?", answer: "1", type: "multiple choice", choices: ["1", "2", "3", "4"] },
    { question: "Which is the heaviest naturally occurring element?", answer: "Uranium", type: "multiple choice", choices: ["Iron", "Copper", "Gold", "Uranium"] },
    { question: "What is the chemical formula for sodium chloride?", answer: "NaCl", type: "multiple choice", choices: ["NaOH", "HCl", "NaCl", "H2SO4"] },
    { question: "What is the process called when a solid changes into a liquid?", answer: "Melting", type: "multiple choice", choices: ["Evaporation", "Condensation", "Melting", "Solidification"] },
    { question: "What is the molar mass of methane (CH4)?", answer: "16 g/mol", type: "multiple choice", choices: ["12 g/mol", "16 g/mol", "28 g/mol", "32 g/mol"] },
    { question: "Which gas is used in photosynthesis?", answer: "Carbon dioxide", type: "multiple choice", choices: ["Oxygen", "Carbon dioxide", "Methane", "Hydrogen"] },
    { question: "What is the process called when a liquid changes into a gas at the surface?", answer: "Vaporization", type: "multiple choice", choices: ["Sublimation", "Evaporation", "Vaporization", "Condensation"] },
    { question: "What is the chemical formula for ammonia?", answer: "NH3", type: "multiple choice", choices: ["H2O", "CH4", "NH3", "CO2"] },
    { question: "What is the SI unit for measuring volume?", answer: "Cubic meter", type: "multiple choice", choices: ["Liter", "Gallon", "Cubic centimeter", "Cubic meter"] },
    { question: "Which subatomic particle has no charge?", answer: "Neutron", type: "multiple choice", choices: ["Proton", "Electron", "Neutron", "Nucleus"] },
    { question: "What is the chemical symbol for silver?", answer: "Ag", type: "multiple choice", choices: ["Fe", "Au", "Ag", "Cu"] },
    { question: "What is the process called when a gas changes into a liquid?", answer: "Liquefaction", type: "multiple choice", choices: ["Sublimation", "Evaporation", "Liquefaction", "Condensation"] },
    { question: "What is the atomic number of nitrogen?", answer: "7", type: "multiple choice", choices: ["4", "6", "7", "8"] },
    { question: "Which element is essential for human bones?", answer: "Calcium", type: "multiple choice", choices: ["Iron", "Zinc", "Calcium", "Sodium"] },
    { question: "What is the formula for calculating work?", answer: "Work = Force * Distance", type: "multiple choice", choices: ["Work = Force + Distance", "Work = Force - Distance", "Work = Force / Distance", "Work = Force * Distance"] },
]

const AP_chemistry = [
    { question: "What is the atomic number of oxygen?", answer: "8", type: "multiple choice", choices: ["6", "7", "8", "9"] },
    { question: "What is the symbol for sodium?", answer: "Na", type: "multiple choice", choices: ["So", "Na", "No", "Ni"] },
    { question: "Which of the following is a noble gas?", answer: "Argon", type: "multiple choice", choices: ["Chlorine", "Argon", "Sulfur", "Fluorine"] },
    { question: "What is the chemical formula for water?", answer: "H2O", type: "multiple choice", choices: ["HO2", "H2O2", "H2O", "H2O3"] },
    { question: "What is the molar mass of carbon dioxide (CO2)?", answer: "44.01 g/mol", type: "type the answer" },
    { question: "Which subatomic particle has a positive charge?", answer: "Proton", type: "multiple choice", choices: ["Neutron", "Proton", "Electron", "Photon"] },
    { question: "What is the process called when a liquid changes to a gas?", answer: "Evaporation", type: "multiple choice", choices: ["Condensation", "Evaporation", "Sublimation", "Deposition"] },
    { question: "Which of the following is an example of an exothermic reaction?", answer: "Burning wood", type: "multiple choice", choices: ["Photosynthesis", "Burning wood", "Electrolysis", "Respiration"] },
    { question: "What is the formula for calculating density?", answer: "Density = mass/volume", type: "type the answer" },
    { question: "Which of the following is a strong acid?", answer: "Hydrochloric acid", type: "multiple choice", choices: ["Acetic acid", "Hydrochloric acid", "Citric acid", "Carbonic acid"] },
    { question: "What is the pH of a neutral solution?", answer: "7", type: "multiple choice", choices: ["1", "7", "10", "14"] },
    { question: "Which type of bond involves the sharing of electrons?", answer: "Covalent bond", type: "multiple choice", choices: ["Ionic bond", "Covalent bond", "Hydrogen bond", "Metallic bond"] },
    { question: "What is the SI unit for measuring pressure?", answer: "Pascal", type: "multiple choice", choices: ["Newton", "Watt", "Pascal", "Ohm"] },
    { question: "What is the balanced equation for the reaction: 2H2 + O2 -> 2H2O?", answer: "2H2 + O2 -> 2H2O", type: "type the answer" },
    { question: "Which of the following is a reducing agent?", answer: "Sodium", type: "multiple choice", choices: ["Oxygen", "Sodium", "Chlorine", "Hydrogen"] },
    { question: "What is the boiling point of water in Celsius?", answer: "100°C", type: "multiple choice", choices: ["0°C", "25°C", "50°C", "100°C"] },
    { question: "Which of the following is an example of a heterogeneous mixture?", answer: "Salad dressing", type: "multiple choice", choices: ["Sugar water", "Salad dressing", "Vinegar", "Salt"] },
    { question: "What is the chemical formula for hydrochloric acid?", answer: "HCl", type: "multiple choice", choices: ["H2SO4", "HNO3", "HCl", "H3PO4"] },
    { question: "What is the oxidation state of oxygen in most compounds?", answer: "-2", type: "multiple choice", choices: ["0", "+1", "-2", "+2"] },
    { question: "Which of the following is a greenhouse gas?", answer: "Carbon dioxide", type: "multiple choice", choices: ["Oxygen", "Nitrogen", "Carbon dioxide", "Argon"] },
    { question: "What is the process called when a solid changes directly to a gas?", answer: "Sublimation", type: "multiple choice", choices: ["Evaporation", "Condensation", "Sublimation", "Deposition"] },
    { question: "What is the balanced equation for the reaction: CH4 + 2O2 -> CO2 + 2H2O?", answer: "CH4 + 2O2 -> CO2 + 2H2O", type: "type the answer" },
    { question: "Which of the following is an example of a Lewis acid?", answer: "Boron trifluoride (BF3)", type: "multiple choice", choices: ["Water (H2O)", "Hydrochloric acid (HCl)", "Ethanol (CH3CH2OH)", "Boron trifluoride (BF3)"] },
    { question: "What is the process called when a gas changes to a liquid?", answer: "Condensation", type: "multiple choice", choices: ["Evaporation", "Condensation", "Sublimation", "Deposition"] },
    { question: "Which of the following is a strong base?", answer: "Sodium hydroxide", type: "multiple choice", choices: ["Ammonia", "Acetic acid", "Sodium hydroxide", "Carbon dioxide"] },
    { question: "What is the chemical formula for methane?", answer: "CH4", type: "multiple choice", choices: ["CO2", "H2O", "CH4", "NH3"] },
    { question: "What is the valence electron configuration of oxygen?", answer: "2-6", type: "type the answer" },
    { question: "Which of the following is an example of an endothermic reaction?", answer: "Photosynthesis", type: "multiple choice", choices: ["Burning wood", "Photosynthesis", "Neutralization", "Combustion"] },
    { question: "What is the SI unit for measuring energy?", answer: "Joule", type: "multiple choice", choices: ["Pascal", "Newton", "Joule", "Watt"] },
    { question: "Which of the following is a type of polymer?", answer: "Polyethylene", type: "multiple choice", choices: ["Copper", "Gold", "Polyethylene", "Aluminum"] },
    { question: "What is the chemical formula for sulfuric acid?", answer: "H2SO4", type: "multiple choice", choices: ["HCl", "HNO3", "H2SO4", "H3PO4"] },
    { question: "What is the pH of a basic solution?", answer: "Greater than 7", type: "multiple choice", choices: ["Less than 7", "Equal to 7", "Greater than 7", "Negative"] },
    { question: "Which of the following is an example of a physical change?", answer: "Melting ice", type: "multiple choice", choices: ["Burning paper", "Digesting food", "Rusting iron", "Melting ice"] },
    { question: "What is the chemical formula for ammonia?", answer: "NH3", type: "multiple choice", choices: ["NO2", "H2SO4", "NH3", "H3PO4"] },
    { question: "Which of the following is a characteristic of an acid?", answer: "Sour taste", type: "multiple choice", choices: ["Bitter taste", "Sour taste", "Slippery feel", "None of the above"] },
    { question: "What is the freezing point of water in Fahrenheit?", answer: "32°F", type: "multiple choice", choices: ["0°F", "25°F", "50°F", "32°F"] },
    { question: "What is the balanced equation for the reaction: 2H2O2 -> 2H2O + O2?", answer: "2H2O2 -> 2H2O + O2", type: "type the answer" },
    { question: "Which of the following is an example of an element?", answer: "Oxygen", type: "multiple choice", choices: ["Water", "Salt", "Sugar", "Oxygen"] },
    { question: "What is the oxidation state of hydrogen in most compounds?", answer: "+1", type: "multiple choice", choices: ["0", "+1", "-1", "+2"] },
    { question: "Which of the following is a greenhouse gas?", answer: "Methane", type: "multiple choice", choices: ["Oxygen", "Carbon dioxide", "Methane", "Nitrogen"] },
    { question: "What is the process called when a gas changes directly to a solid?", answer: "Deposition", type: "multiple choice", choices: ["Evaporation", "Condensation", "Sublimation", "Deposition"] },
    { question: "What is the balanced equation for the reaction: 2Na + Cl2 -> 2NaCl?", answer: "2Na + Cl2 -> 2NaCl", type: "type the answer" },
    { question: "Which of the following is an example of a Lewis base?", answer: "Ammonia (NH3)", type: "multiple choice", choices: ["Water (H2O)", "Hydrochloric acid (HCl)", "Ethanol (CH3CH2OH)", "Ammonia (NH3)"] },
    { question: "What is the process called when a liquid changes to a solid?", answer: "Freezing", type: "multiple choice", choices: ["Evaporation", "Condensation", "Freezing", "Deposition"] },
    { question: "Which of the following is a weak acid?", answer: "Acetic acid", type: "multiple choice", choices: ["Hydrochloric acid", "Sulfuric acid", "Acetic acid", "Nitric acid"] },
    { question: "What is the chemical formula for carbon monoxide?", answer: "CO", type: "multiple choice", choices: ["CO2", "H2O", "CO", "NH3"] },
    { question: "What is the electron configuration of chlorine?", answer: "2-8-7", type: "type the answer" },
    { question: "Which of the following is an example of an exothermic process?", answer: "Freezing water", type: "multiple choice", choices: ["Melting ice", "Boiling water", "Evaporating alcohol", "Freezing water"] },
    { question: "What is the SI unit for measuring temperature?", answer: "Kelvin", type: "multiple choice", choices: ["Celsius", "Fahrenheit", "Kelvin", "Rankine"] },
    { question: "Which of the following is a type of colloid?", answer: "Milk", type: "multiple choice", choices: ["Saltwater", "Orange juice", "Milk", "Tap water"] },
]

const physics = [
    { question: "What is the SI unit for measuring time?", answer: "Second", type: "multiple choice", choices: ["Meter", "Second", "Kilogram", "Ampere"] },
    { question: "Which of the following is an example of a scalar quantity?", answer: "Temperature", type: "multiple choice", choices: ["Velocity", "Force", "Acceleration", "Temperature"] },
    { question: "What is the formula for calculating speed?", answer: "Speed = Distance / Time", type: "multiple choice", choices: ["Speed = Distance * Time", "Speed = Distance + Time", "Speed = Distance - Time", "Speed = Distance / Time"] },
    { question: "Which law states that an object at rest will stay at rest, and an object in motion will stay in motion with the same speed and direction, unless acted upon by an external force?", answer: "Newton's First Law of Motion", type: "multiple choice", choices: ["Newton's First Law of Motion", "Newton's Second Law of Motion", "Newton's Third Law of Motion", "Law of Conservation of Energy"] },
    { question: "What is the acceleration due to gravity on Earth?", answer: "9.8 m/s^2", type: "multiple choice", choices: ["3.14 m/s^2", "6.7 m/s^2", "9.8 m/s^2", "12.3 m/s^2"] },
    { question: "What is the unit for measuring force?", answer: "Newton", type: "multiple choice", choices: ["Watt", "Joule", "Newton", "Pascal"] },
    { question: "What is the relationship between force, mass, and acceleration?", answer: "Force = Mass * Acceleration", type: "multiple choice", choices: ["Force = Mass / Acceleration", "Force = Mass + Acceleration", "Force = Mass - Acceleration", "Force = Mass * Acceleration"] },
    { question: "Which type of energy is associated with the motion of an object?", answer: "Kinetic energy", type: "multiple choice", choices: ["Potential energy", "Thermal energy", "Chemical energy", "Kinetic energy"] },
    { question: "What is the formula for calculating work?", answer: "Work = Force * Distance * Cosine(theta)", type: "multiple choice", choices: ["Work = Force * Distance", "Work = Force / Distance", "Work = Force + Distance", "Work = Force * Distance * Cosine(theta)"] },
    { question: "What is the law of conservation of energy?", answer: "Energy cannot be created or destroyed, only transferred or transformed", type: "multiple choice", choices: ["Energy increases with time", "Energy decreases with time", "Energy can be created from nothing", "Energy cannot be created or destroyed, only transferred or transformed"] },
    { question: "What is the unit for measuring electric current?", answer: "Ampere", type: "multiple choice", choices: ["Ohm", "Joule", "Ampere", "Volt"] },
    { question: "What is the formula for calculating power?", answer: "Power = Work / Time", type: "multiple choice", choices: ["Power = Work * Time", "Power = Work + Time", "Power = Work - Time", "Power = Work / Time"] },
    { question: "What is the unit for measuring electric resistance?", answer: "Ohm", type: "multiple choice", choices: ["Ampere", "Ohm", "Joule", "Volt"] },
    { question: "What is the formula for calculating electric power?", answer: "Power = Voltage * Current", type: "multiple choice", choices: ["Power = Voltage / Current", "Power = Voltage + Current", "Power = Voltage - Current", "Power = Voltage * Current"] },
    { question: "Which law states that the total electric charge of a closed system is constant?", answer: "Law of Conservation of Electric Charge", type: "multiple choice", choices: ["Coulomb's Law", "Ohm's Law", "Law of Conservation of Energy", "Law of Conservation of Electric Charge"] },
    { question: "What is the SI unit for measuring electric charge?", answer: "Coulomb", type: "multiple choice", choices: ["Ampere", "Ohm", "Joule", "Coulomb"] },
    { question: "Which type of lens can converge light rays?", answer: "Convex lens", type: "multiple choice", choices: ["Concave lens", "Convex lens", "Plano-convex lens", "Biconvex lens"] },
    { question: "What is the law of reflection?", answer: "The angle of incidence is equal to the angle of reflection", type: "multiple choice", choices: ["The angle of incidence is greater than the angle of reflection", "The angle of incidence is less than the angle of reflection", "The angle of incidence is equal to the angle of reflection", "The angle of incidence has no relation to the angle of reflection"] },
    { question: "What is the unit for measuring electric potential difference?", answer: "Volt", type: "multiple choice", choices: ["Ohm", "Ampere", "Joule", "Volt"] },
    { question: "Which law states that the current flowing through a conductor is directly proportional to the voltage and inversely proportional to the resistance?", answer: "Ohm's Law", type: "multiple choice", choices: ["Newton's Law of Gravitation", "Coulomb's Law", "Faraday's Law", "Ohm's Law"] },
    { question: "What is the unit for measuring frequency?", answer: "Hertz", type: "multiple choice", choices: ["Meter", "Second", "Kilogram", "Hertz"] },
    { question: "Which type of waves require a medium to travel through?", answer: "Mechanical waves", type: "multiple choice", choices: ["Electromagnetic waves", "Mechanical waves", "Transverse waves", "Longitudinal waves"] },
    { question: "What is the relationship between wavelength and frequency?", answer: "Inverse relationship", type: "multiple choice", choices: ["Direct relationship", "Inverse relationship", "No relationship", "Exponential relationship"] },
    { question: "Which type of circuit has only one path for the current to flow through?", answer: "Series circuit", type: "multiple choice", choices: ["Parallel circuit", "Series circuit", "Combination circuit", "Open circuit"] },
    { question: "What is the SI unit for measuring force?", answer: "Newton", type: "multiple choice", choices: ["Watt", "Joule", "Newton", "Pascal"] },
    { question: "Which law states that the pressure of a gas is inversely proportional to its volume when temperature is constant?", answer: "Boyle's Law", type: "multiple choice", choices: ["Charles's Law", "Gay-Lussac's Law", "Avogadro's Law", "Boyle's Law"] },
    { question: "What is the formula for calculating mechanical advantage?", answer: "Mechanical Advantage = Output Force / Input Force", type: "multiple choice", choices: ["Mechanical Advantage = Output Force * Input Force", "Mechanical Advantage = Output Force - Input Force", "Mechanical Advantage = Output Force + Input Force", "Mechanical Advantage = Output Force / Input Force"] },
    { question: "What is the unit for measuring energy?", answer: "Joule", type: "multiple choice", choices: ["Newton", "Pascal", "Watt", "Joule"] },
    { question: "Which law states that the total resistance in a series circuit is equal to the sum of individual resistances?", answer: "Kirchhoff's First Law (Voltage Law)", type: "multiple choice", choices: ["Kirchhoff's First Law (Voltage Law)", "Kirchhoff's Second Law (Current Law)", "Faraday's Law", "Ohm's Law"] },
    { question: "What is the unit for measuring power?", answer: "Watt", type: "multiple choice", choices: ["Ohm", "Ampere", "Joule", "Watt"] },
    { question: "Which type of waves have oscillations perpendicular to the direction of wave propagation?", answer: "Transverse waves", type: "multiple choice", choices: ["Electromagnetic waves", "Mechanical waves", "Transverse waves", "Longitudinal waves"] },
    { question: "What is the law of conservation of momentum?", answer: "The total momentum of an isolated system remains constant", type: "multiple choice", choices: ["The total momentum of an isolated system increases with time", "The total momentum of an isolated system decreases with time", "The total momentum of an isolated system is zero", "The total momentum of an isolated system remains constant"] },
    { question: "Which type of lens can diverge light rays?", answer: "Concave lens", type: "multiple choice", choices: ["Convex lens", "Concave lens", "Plano-concave lens", "Biconcave lens"] },
    { question: "What is the unit for measuring electric current?", answer: "Ampere", type: "multiple choice", choices: ["Ohm", "Joule", "Ampere", "Volt"] },
    { question: "Which type of energy is associated with the position or condition of an object?", answer: "Potential energy", type: "multiple choice", choices: ["Kinetic energy", "Thermal energy", "Chemical energy", "Potential energy"] },
    { question: "What is the formula for calculating force?", answer: "Force = Mass * Acceleration", type: "multiple choice", choices: ["Force = Mass / Acceleration", "Force = Mass + Acceleration", "Force = Mass - Acceleration", "Force = Mass * Acceleration"] },
    { question: "What is the unit for measuring electric power?", answer: "Watt", type: "multiple choice", choices: ["Ohm", "Joule", "Ampere", "Watt"] },
    { question: "Which type of circuit has multiple paths for the current to flow through?", answer: "Parallel circuit", type: "multiple choice", choices: ["Series circuit", "Parallel circuit", "Combination circuit", "Short circuit"] },
    { question: "What is the formula for calculating frequency?", answer: "Frequency = 1 / Period", type: "multiple choice", choices: ["Frequency = Period / 1", "Frequency = Period * 1", "Frequency = Period + 1", "Frequency = 1 / Period"] },
    { question: "Which law states that the resistance of a conductor is directly proportional to its length and inversely proportional to its cross-sectional area?", answer: "Ohm's Law", type: "multiple choice", choices: ["Boyle's Law", "Coulomb's Law", "Faraday's Law", "Ohm's Law"] },
    { question: "What is the SI unit for measuring power?", answer: "Watt", type: "multiple choice", choices: ["Ohm", "Ampere", "Joule", "Watt"] },
    { question: "Which law states that the net force acting on an object is equal to the mass of the object multiplied by its acceleration?", answer: "Newton's Second Law of Motion", type: "multiple choice", choices: ["Newton's First Law of Motion", "Newton's Second Law of Motion", "Newton's Third Law of Motion", "Law of Conservation of Energy"] },
    { question: "What is the unit for measuring wavelength?", answer: "Meter", type: "multiple choice", choices: ["Meter", "Second", "Kilogram", "Hertz"] },
    { question: "Which type of waves have oscillations parallel to the direction of wave propagation?", answer: "Longitudinal waves", type: "multiple choice", choices: ["Electromagnetic waves", "Mechanical waves", "Transverse waves", "Longitudinal waves"] },
    { question: "What is the law of conservation of angular momentum?", answer: "The total angular momentum of an isolated system remains constant", type: "multiple choice", choices: ["The total angular momentum of an isolated system increases with time", "The total angular momentum of an isolated system decreases with time", "The total angular momentum of an isolated system is zero", "The total angular momentum of an isolated system remains constant"] },
    { question: "What is the unit for measuring electric charge?", answer: "Coulomb", type: "multiple choice", choices: ["Ampere", "Ohm", "Joule", "Coulomb"] },
    { question: "Which law states that the pressure of a gas is directly proportional to its temperature when volume is constant?", answer: "Gay-Lussac's Law", type: "multiple choice", choices: ["Boyle's Law", "Charles's Law", "Avogadro's Law", "Gay-Lussac's Law"] },
    { question: "What is the formula for calculating gravitational potential energy?", answer: "Gravitational Potential Energy = Mass * Gravity * Height", type: "multiple choice", choices: ["Gravitational Potential Energy = Mass / Gravity / Height", "Gravitational Potential Energy = Mass + Gravity + Height", "Gravitational Potential Energy = Mass - Gravity - Height", "Gravitational Potential Energy = Mass * Gravity * Height"] },
    { question: "What is the unit for measuring electric resistance?", answer: "Ohm", type: "multiple choice", choices: ["Ampere", "Ohm", "Joule", "Volt"] },
    { question: "Which type of circuit has a combination of series and parallel connections?", answer: "Combination circuit", type: "multiple choice", choices: ["Series circuit", "Parallel circuit", "Combination circuit", "Closed circuit"] },
]

const AP_physics = [
    { question: "What is the SI unit for measuring force?", answer: "Newton", type: "multiple choice", choices: ["Watt", "Joule", "Newton", "Coulomb"] },
    { question: "Which type of motion is described by a constant velocity?", answer: "Uniform motion", type: "multiple choice", choices: ["Uniform motion", "Accelerated motion", "Circular motion", "Simple harmonic motion"] },
    { question: "What is the formula for calculating velocity?", answer: "Velocity = Displacement / Time", type: "multiple choice", choices: ["Velocity = Displacement * Time", "Velocity = Displacement + Time", "Velocity = Displacement - Time", "Velocity = Displacement / Time"] },
    { question: "Which law states that every action has an equal and opposite reaction?", answer: "Newton's Third Law of Motion", type: "multiple choice", choices: ["Newton's First Law of Motion", "Newton's Second Law of Motion", "Newton's Third Law of Motion", "Law of Conservation of Energy"] },
    { question: "What is the unit for measuring electric potential difference?", answer: "Volt", type: "multiple choice", choices: ["Ohm", "Joule", "Ampere", "Volt"] },
    { question: "Which type of circuit has only one path for the current to flow through?", answer: "Series circuit", type: "multiple choice", choices: ["Series circuit", "Parallel circuit", "Combination circuit", "Open circuit"] },
    { question: "What is the formula for calculating work?", answer: "Work = Force * Distance * cos(theta)", type: "multiple choice", choices: ["Work = Force / Distance * cos(theta)", "Work = Force + Distance * cos(theta)", "Work = Force - Distance * cos(theta)", "Work = Force * Distance * cos(theta)"] },
    { question: "Which law states that the volume of a gas is inversely proportional to its pressure when temperature is constant?", answer: "Boyle's Law", type: "multiple choice", choices: ["Boyle's Law", "Charles's Law", "Avogadro's Law", "Gay-Lussac's Law"] },
    { question: "What is the formula for calculating acceleration?", answer: "Acceleration = (Final Velocity - Initial Velocity) / Time", type: "multiple choice", choices: ["Acceleration = (Final Velocity + Initial Velocity) / Time", "Acceleration = (Final Velocity - Initial Velocity) * Time", "Acceleration = (Final Velocity / Initial Velocity) / Time", "Acceleration = (Final Velocity - Initial Velocity) / Time"] },
    { question: "What is the unit for measuring electric current?", answer: "Ampere", type: "multiple choice", choices: ["Ohm", "Joule", "Ampere", "Volt"] },
    { question: "Which type of mirror forms a virtual, upright, and diminished image?", answer: "Concave mirror", type: "multiple choice", choices: ["Convex mirror", "Concave mirror", "Plane mirror", "Cylindrical mirror"] },
    { question: "What is the law of conservation of energy?", answer: "Energy cannot be created or destroyed, only transferred or transformed", type: "multiple choice", choices: ["Energy increases with time", "Energy decreases with time", "Energy is zero in a closed system", "Energy cannot be created or destroyed, only transferred or transformed"] },
    { question: "What is the unit for measuring electric charge?", answer: "Coulomb", type: "multiple choice", choices: ["Ampere", "Ohm", "Joule", "Coulomb"] },
    { question: "Which type of lens can converge light rays?", answer: "Converging lens", type: "multiple choice", choices: ["Diverging lens", "Converging lens", "Plane lens", "Cylindrical lens"] },
    { question: "What is the formula for calculating power?", answer: "Power = Work / Time", type: "multiple choice", choices: ["Power = Work * Time", "Power = Work + Time", "Power = Work - Time", "Power = Work / Time"] },
    { question: "Which law states that the resistance of a conductor is directly proportional to its length and inversely proportional to its cross-sectional area?", answer: "Ohm's Law", type: "multiple choice", choices: ["Boyle's Law", "Coulomb's Law", "Faraday's Law", "Ohm's Law"] },
    { question: "What is the SI unit for measuring power?", answer: "Watt", type: "multiple choice", choices: ["Ohm", "Ampere", "Joule", "Watt"] },
    { question: "Which law states that the net force acting on an object is equal to the mass of the object multiplied by its acceleration?", answer: "Newton's Second Law of Motion", type: "multiple choice", choices: ["Newton's First Law of Motion", "Newton's Second Law of Motion", "Newton's Third Law of Motion", "Law of Conservation of Energy"] },
    { question: "What is the unit for measuring wavelength?", answer: "Meter", type: "multiple choice", choices: ["Meter", "Second", "Kilogram", "Hertz"] },
    { question: "Which type of waves have oscillations parallel to the direction of wave propagation?", answer: "Longitudinal waves", type: "multiple choice", choices: ["Electromagnetic waves", "Mechanical waves", "Transverse waves", "Longitudinal waves"] },
    { question: "What is the law of conservation of angular momentum?", answer: "The total angular momentum of an isolated system remains constant", type: "multiple choice", choices: ["The total angular momentum of an isolated system increases with time", "The total angular momentum of an isolated system decreases with time", "The total angular momentum of an isolated system is zero", "The total angular momentum of an isolated system remains constant"] },
    { question: "What is the unit for measuring electric resistance?", answer: "Ohm", type: "multiple choice", choices: ["Ampere", "Ohm", "Joule", "Volt"] },
    { question: "Which law states that the pressure of a gas is directly proportional to its temperature when volume is constant?", answer: "Gay-Lussac's Law", type: "multiple choice", choices: ["Boyle's Law", "Charles's Law", "Avogadro's Law", "Gay-Lussac's Law"] },
    { question: "What is the formula for calculating gravitational potential energy?", answer: "Gravitational Potential Energy = Mass * Gravity * Height", type: "multiple choice", choices: ["Gravitational Potential Energy = Mass / Gravity / Height", "Gravitational Potential Energy = Mass + Gravity + Height", "Gravitational Potential Energy = Mass - Gravity - Height", "Gravitational Potential Energy = Mass * Gravity * Height"] },
    { question: "What is the unit for measuring electric resistance?", answer: "Ohm", type: "multiple choice", choices: ["Ampere", "Ohm", "Joule", "Volt"] },
    { question: "Which type of lens can diverge light rays?", answer: "Diverging lens", type: "multiple choice", choices: ["Converging lens", "Diverging lens", "Plane lens", "Cylindrical lens"] },
    { question: "What is the formula for calculating momentum?", answer: "Momentum = Mass * Velocity", type: "multiple choice", choices: ["Momentum = Mass / Velocity", "Momentum = Mass + Velocity", "Momentum = Mass - Velocity", "Momentum = Mass * Velocity"] },
    { question: "Which law states that the current flowing through a conductor is directly proportional to the voltage applied across it?", answer: "Ohm's Law", type: "multiple choice", choices: ["Boyle's Law", "Coulomb's Law", "Faraday's Law", "Ohm's Law"] },
    { question: "What is the SI unit for measuring frequency?", answer: "Hertz", type: "multiple choice", choices: ["Meter", "Second", "Kilogram", "Hertz"] },
    { question: "Which type of waves have oscillations perpendicular to the direction of wave propagation?", answer: "Transverse waves", type: "multiple choice", choices: ["Electromagnetic waves", "Mechanical waves", "Transverse waves", "Longitudinal waves"] },
    { question: "What is the law of conservation of energy?", answer: "Energy cannot be created or destroyed, only transferred or transformed", type: "multiple choice", choices: ["Energy increases with time", "Energy decreases with time", "Energy is zero in a closed system", "Energy cannot be created or destroyed, only transferred or transformed"] },
    { question: "What is the unit for measuring electric power?", answer: "Watt", type: "multiple choice", choices: ["Ohm", "Ampere", "Joule", "Watt"] },
    { question: "Which law states that the resistance of a conductor is directly proportional to its length and inversely proportional to its cross-sectional area?", answer: "Ohm's Law", type: "multiple choice", choices: ["Boyle's Law", "Coulomb's Law", "Faraday's Law", "Ohm's Law"] },
    { question: "What is the SI unit for measuring power?", answer: "Watt", type: "multiple choice", choices: ["Ohm", "Ampere", "Joule", "Watt"] },
    { question: "Which law states that the net force acting on an object is equal to the mass of the object multiplied by its acceleration?", answer: "Newton's Second Law of Motion", type: "multiple choice", choices: ["Newton's First Law of Motion", "Newton's Second Law of Motion", "Newton's Third Law of Motion", "Law of Conservation of Energy"] },
    { question: "What is the unit for measuring wavelength?", answer: "Meter", type: "multiple choice", choices: ["Meter", "Second", "Kilogram", "Hertz"] },
    { question: "Which type of waves have oscillations parallel to the direction of wave propagation?", answer: "Longitudinal waves", type: "multiple choice", choices: ["Electromagnetic waves", "Mechanical waves", "Transverse waves", "Longitudinal waves"] },
    { question: "What is the law of conservation of angular momentum?", answer: "The total angular momentum of an isolated system remains constant", type: "multiple choice", choices: ["The total angular momentum of an isolated system increases with time", "The total angular momentum of an isolated system decreases with time", "The total angular momentum of an isolated system is zero", "The total angular momentum of an isolated system remains constant"] },
    { question: "What is the unit for measuring electric resistance?", answer: "Ohm", type: "multiple choice", choices: ["Ampere", "Ohm", "Joule", "Volt"] },
    { question: "Which law states that the pressure of a gas is directly proportional to its temperature when volume is constant?", answer: "Gay-Lussac's Law", type: "multiple choice", choices: ["Boyle's Law", "Charles's Law", "Avogadro's Law", "Gay-Lussac's Law"] },
    { question: "What is the formula for calculating gravitational potential energy?", answer: "Gravitational Potential Energy = Mass * Gravity * Height", type: "multiple choice", choices: ["Gravitational Potential Energy = Mass / Gravity / Height", "Gravitational Potential Energy = Mass + Gravity + Height", "Gravitational Potential Energy = Mass - Gravity - Height", "Gravitational Potential Energy = Mass * Gravity * Height"] },
    { question: "What is the unit for measuring electric resistance?", answer: "Ohm", type: "multiple choice", choices: ["Ampere", "Ohm", "Joule", "Volt"] },
    { question: "Which type of lens can diverge light rays?", answer: "Diverging lens", type: "multiple choice", choices: ["Converging lens", "Diverging lens", "Plane lens", "Cylindrical lens"] },
    { question: "What is the formula for calculating momentum?", answer: "Momentum = Mass * Velocity", type: "multiple choice", choices: ["Momentum = Mass / Velocity", "Momentum = Mass + Velocity", "Momentum = Mass - Velocity", "Momentum = Mass * Velocity"] },
    { question: "Which law states that the current flowing through a conductor is directly proportional to the voltage applied across it?", answer: "Ohm's Law", type: "multiple choice", choices: ["Boyle's Law", "Coulomb's Law", "Faraday's Law", "Ohm's Law"] },
    { question: "What is the SI unit for measuring frequency?", answer: "Hertz", type: "multiple choice", choices: ["Meter", "Second", "Kilogram", "Hertz"] },
    { question: "Which type of waves have oscillations perpendicular to the direction of wave propagation?", answer: "Transverse waves", type: "multiple choice", choices: ["Electromagnetic waves", "Mechanical waves", "Transverse waves", "Longitudinal waves"] },
    { question: "What is the law of conservation of energy?", answer: "Energy cannot be created or destroyed, only transferred or transformed", type: "multiple choice", choices: ["Energy increases with time", "Energy decreases with time", "Energy is zero in a closed system", "Energy cannot be created or destroyed, only transferred or transformed"] },
    { question: "What is the unit for measuring electric power?", answer: "Watt", type: "multiple choice", choices: ["Ohm", "Ampere", "Joule", "Watt"] },
    { question: "Which law states that the resistance of a conductor is directly proportional to its length and inversely proportional to its cross-sectional area?", answer: "Ohm's Law", type: "multiple choice", choices: ["Boyle's Law", "Coulomb's Law", "Faraday's Law", "Ohm's Law"] }
]

const grade6_science = [
    { question: "Which of the following is a renewable resource?", answer: "Wind energy", type: "multiple choice", choices: ["Coal", "Natural gas", "Wind energy", "Uranium"] },
    { question: "What is the process by which plants make food using sunlight?", answer: "Photosynthesis", type: "multiple choice", choices: ["Cellular respiration", "Photosynthesis", "Fermentation", "Evaporation"] },
    { question: "Which of the following is an example of a physical change?", answer: "Melting ice", type: "multiple choice", choices: ["Burning wood", "Cooking an egg", "Melting ice", "Rusting metal"] },
    { question: "What is the basic unit of life?", answer: "Cell", type: "multiple choice", choices: ["Atom", "Molecule", "Cell", "Organism"] },
    { question: "Which of the following is a conductor of electricity?", answer: "Copper", type: "multiple choice", choices: ["Rubber", "Copper", "Plastic", "Wood"] },
    { question: "What is the force that pulls objects towards the center of the Earth?", answer: "Gravity", type: "multiple choice", choices: ["Magnetism", "Friction", "Gravity", "Inertia"] },
    { question: "Which of the following is a renewable energy source?", answer: "Solar power", type: "multiple choice", choices: ["Coal", "Oil", "Natural gas", "Solar power"] },
    { question: "What is the process by which water changes from a liquid to a gas?", answer: "Evaporation", type: "multiple choice", choices: ["Condensation", "Precipitation", "Evaporation", "Sublimation"] },
    { question: "What is the measurement of the force of gravity on an object?", answer: "Weight", type: "multiple choice", choices: ["Mass", "Volume", "Density", "Weight"] },
    { question: "Which of the following is an example of a chemical change?", answer: "Burning paper", type: "multiple choice", choices: ["Melting ice", "Boiling water", "Burning paper", "Mixing salt and water"] },
    { question: "Which of the following is the largest planet in our solar system?", answer: "Jupiter", type: "multiple choice", choices: ["Mars", "Saturn", "Jupiter", "Venus"] },
    { question: "What is the process by which rocks are broken down into smaller pieces by wind or water?", answer: "Weathering", type: "multiple choice", choices: ["Erosion", "Deposition", "Weathering", "Compaction"] },
    { question: "Which of the following is the smallest particle of an element that retains its properties?", answer: "Atom", type: "multiple choice", choices: ["Molecule", "Cell", "Atom", "Compound"] },
    { question: "What is the source of energy that powers the water cycle?", answer: "The Sun", type: "multiple choice", choices: ["The Moon", "The Sun", "The Earth's core", "Fossil fuels"] },
    { question: "Which of the following is a non-renewable resource?", answer: "Natural gas", type: "multiple choice", choices: ["Solar power", "Wind energy", "Hydroelectric power", "Natural gas"] },
    { question: "What is the process by which plants release water vapor into the air?", answer: "Transpiration", type: "multiple choice", choices: ["Precipitation", "Condensation", "Transpiration", "Infiltration"] },
    { question: "Which of the following is a mixture?", answer: "Air", type: "multiple choice", choices: ["Salt", "Sugar", "Water", "Air"] },
    { question: "What is the process by which liquid water changes into a solid?", answer: "Freezing", type: "multiple choice", choices: ["Melting", "Evaporation", "Condensation", "Freezing"] },
    { question: "Which of the following is the primary function of the respiratory system?", answer: "To take in oxygen and release carbon dioxide", type: "multiple choice", choices: ["To pump blood throughout the body", "To break down food and absorb nutrients", "To take in oxygen and release carbon dioxide", "To remove waste from the body"] },
    { question: "What is the layer of the Earth's atmosphere where weather occurs?", answer: "Troposphere", type: "multiple choice", choices: ["Stratosphere", "Mesosphere", "Troposphere", "Exosphere"] },
    { question: "Which of the following is an example of an insulator?", answer: "Rubber", type: "multiple choice", choices: ["Copper", "Aluminum", "Silver", "Rubber"] },
    { question: "What is the process by which plants and animals release energy from food?", answer: "Cellular respiration", type: "multiple choice", choices: ["Photosynthesis", "Fermentation", "Evaporation", "Cellular respiration"] },
    { question: "Which of the following is an example of a simple machine?", answer: "Lever", type: "multiple choice", choices: ["Battery", "Motor", "Generator", "Lever"] },
    { question: "What is the process by which plants make food in the absence of sunlight?", answer: "Fermentation", type: "multiple choice", choices: ["Photosynthesis", "Cellular respiration", "Evaporation", "Fermentation"] },
    { question: "Which of the following is a type of energy associated with motion?", answer: "Kinetic energy", type: "multiple choice", choices: ["Potential energy", "Thermal energy", "Chemical energy", "Kinetic energy"] },
    { question: "What is the process by which an organism changes over time to better survive in its environment?", answer: "Adaptation", type: "multiple choice", choices: ["Reproduction", "Growth", "Adaptation", "Mutation"] },
    { question: "Which of the following is a source of renewable energy?", answer: "Hydroelectric power", type: "multiple choice", choices: ["Natural gas", "Coal", "Nuclear power", "Hydroelectric power"] },
    { question: "What is the force that resists the motion of objects moving through air or water?", answer: "Drag", type: "multiple choice", choices: ["Friction", "Gravity", "Inertia", "Drag"] },
    { question: "Which of the following is the hardest mineral?", answer: "Diamond", type: "multiple choice", choices: ["Quartz", "Feldspar", "Calcite", "Diamond"] },
    { question: "What is the process by which plants take in carbon dioxide and release oxygen?", answer: "Photosynthesis", type: "multiple choice", choices: ["Cellular respiration", "Photosynthesis", "Fermentation", "Evaporation"] },
    { question: "Which of the following is a type of energy associated with the position of an object?", answer: "Potential energy", type: "multiple choice", choices: ["Kinetic energy", "Thermal energy", "Chemical energy", "Potential energy"] },
    { question: "What is the layer of the Earth's atmosphere that contains the ozone layer?", answer: "Stratosphere", type: "multiple choice", choices: ["Troposphere", "Mesosphere", "Stratosphere", "Exosphere"] },
    { question: "Which of the following is an example of a producer in an ecosystem?", answer: "Grass", type: "multiple choice", choices: ["Lion", "Tiger", "Elephant", "Grass"] },
    { question: "What is the process by which sediment is dropped off in a new location?", answer: "Deposition", type: "multiple choice", choices: ["Weathering", "Erosion", "Deposition", "Compaction"] },
    { question: "Which of the following is a characteristic of a solid?", answer: "Definite shape and volume", type: "multiple choice", choices: ["Definite volume but not shape", "Definite shape but not volume", "Neither definite shape nor volume", "Definite shape and volume"] },
    { question: "What is the layer of the Earth's atmosphere that contains the ozone layer?", answer: "Stratosphere", type: "multiple choice", choices: ["Troposphere", "Mesosphere", "Stratosphere", "Exosphere"] },
    { question: "Which of the following is an example of a conductor of electricity?", answer: "Copper", type: "multiple choice", choices: ["Rubber", "Plastic", "Glass", "Copper"] },
    { question: "What is the force that pulls objects towards the center of the Earth?", answer: "Gravity", type: "multiple choice", choices: ["Magnetism", "Friction", "Gravity", "Inertia"] },
    { question: "Which of the following is the largest planet in our solar system?", answer: "Jupiter", type: "multiple choice", choices: ["Mars", "Saturn", "Jupiter", "Venus"] },
    { question: "What is the process by which rocks are broken down into smaller pieces by wind or water?", answer: "Weathering", type: "multiple choice", choices: ["Erosion", "Deposition", "Weathering", "Compaction"] },
    { question: "Which of the following is the smallest particle of an element that retains its properties?", answer: "Atom", type: "multiple choice", choices: ["Molecule", "Cell", "Atom", "Compound"] },
    { question: "What is the source of energy that powers the water cycle?", answer: "The Sun", type: "multiple choice", choices: ["The Moon", "The Sun", "The Earth's core", "Fossil fuels"] },
    { question: "Which of the following is a non-renewable resource?", answer: "Natural gas", type: "multiple choice", choices: ["Solar power", "Wind energy", "Hydroelectric power", "Natural gas"] },
    { question: "What is the process by which water changes from a liquid to a gas?", answer: "Evaporation", type: "multiple choice", choices: ["Condensation", "Precipitation", "Evaporation", "Sublimation"] },
    { question: "What is the measurement of the force of gravity on an object?", answer: "Weight", type: "multiple choice", choices: ["Mass", "Volume", "Density", "Weight"] },
    { question: "Which of the following is an example of a chemical change?", answer: "Burning paper", type: "multiple choice", choices: ["Melting ice", "Boiling water", "Burning paper", "Mixing salt and water"] },
    { question: "Which of the following is a renewable resource?", answer: "Wind energy", type: "multiple choice", choices: ["Coal", "Natural gas", "Wind energy", "Uranium"] },
    { question: "What is the process by which plants make food using sunlight?", answer: "Photosynthesis", type: "multiple choice", choices: ["Cellular respiration", "Photosynthesis", "Fermentation", "Evaporation"] },
    { question: "Which of the following is an example of a physical change?", answer: "Melting ice", type: "multiple choice", choices: ["Burning wood", "Cooking an egg", "Melting ice", "Rusting metal"] },
    { question: "What is the basic unit of life?", answer: "Cell", type: "multiple choice", choices: ["Atom", "Molecule", "Cell", "Organism"] }
]

const grade7_science = [
    { question: "What is the basic unit of life?", answer: "Cell", type: "multiple choice", choices: ["Atom", "Molecule", "Cell", "Organism"] },
    { question: "What is the process by which plants make food using sunlight?", answer: "Photosynthesis", type: "multiple choice", choices: ["Cellular respiration", "Photosynthesis", "Fermentation", "Evaporation"] },
    { question: "Which of the following is an example of a renewable resource?", answer: "Solar energy", type: "multiple choice", choices: ["Coal", "Natural gas", "Solar energy", "Uranium"] },
    { question: "What is the measurement of the force of gravity on an object?", answer: "Weight", type: "multiple choice", choices: ["Mass", "Volume", "Density", "Weight"] },
    { question: "Which of the following is an example of a physical change?", answer: "Melting ice", type: "multiple choice", choices: ["Burning wood", "Cooking an egg", "Melting ice", "Rusting metal"] },
    { question: "What is the layer of the Earth's atmosphere that contains the ozone layer?", answer: "Stratosphere", type: "multiple choice", choices: ["Troposphere", "Mesosphere", "Stratosphere", "Exosphere"] },
    { question: "What is the force that pulls objects towards the center of the Earth?", answer: "Gravity", type: "multiple choice", choices: ["Magnetism", "Friction", "Gravity", "Inertia"] },
    { question: "Which of the following is an example of a conductor of electricity?", answer: "Copper", type: "multiple choice", choices: ["Rubber", "Plastic", "Glass", "Copper"] },
    { question: "What is the process by which sediment is dropped off in a new location?", answer: "Deposition", type: "multiple choice", choices: ["Weathering", "Erosion", "Deposition", "Compaction"] },
    { question: "What is the source of energy that powers the water cycle?", answer: "The Sun", type: "multiple choice", choices: ["The Moon", "The Sun", "The Earth's core", "Fossil fuels"] },
    { question: "Which of the following is an example of a chemical change?", answer: "Burning paper", type: "multiple choice", choices: ["Melting ice", "Boiling water", "Burning paper", "Mixing salt and water"] },
    { question: "What is the process by which rocks are broken down into smaller pieces by wind or water?", answer: "Weathering", type: "multiple choice", choices: ["Erosion", "Deposition", "Weathering", "Compaction"] },
    { question: "What is the layer of the Earth's atmosphere that contains the ozone layer?", answer: "Stratosphere", type: "multiple choice", choices: ["Troposphere", "Mesosphere", "Stratosphere", "Exosphere"] },
    { question: "Which of the following is an example of a producer in an ecosystem?", answer: "Grass", type: "multiple choice", choices: ["Lion", "Tiger", "Elephant", "Grass"] },
    { question: "Which of the following is a characteristic of a solid?", answer: "Definite shape and volume", type: "multiple choice", choices: ["Definite shape and volume", "Definite shape and indefinite volume", "Indefinite shape and definite volume", "Indefinite shape and volume"] },
    { question: "What is the process by which plants release water vapor through their leaves?", answer: "Transpiration", type: "multiple choice", choices: ["Evaporation", "Condensation", "Precipitation", "Transpiration"] },
    { question: "Which of the following is an example of a nonrenewable resource?", answer: "Coal", type: "multiple choice", choices: ["Wind energy", "Solar energy", "Coal", "Hydroelectric power"] },
    { question: "What is the force that opposes the motion of objects through air or water?", answer: "Drag", type: "multiple choice", choices: ["Gravity", "Magnetism", "Friction", "Drag"] },
    { question: "What is the process by which water changes from a liquid to a gas?", answer: "Evaporation", type: "multiple choice", choices: ["Condensation", "Precipitation", "Evaporation", "Transpiration"] },
    { question: "Which of the following is an example of a mixture?", answer: "Saltwater", type: "multiple choice", choices: ["Oxygen", "Hydrogen", "Saltwater", "Gold"] },
    { question: "What is the layer of the Earth's atmosphere where weather occurs?", answer: "Troposphere", type: "multiple choice", choices: ["Stratosphere", "Mesosphere", "Troposphere", "Thermosphere"] },
    { question: "What is the process by which sediment is carried away by wind or water?", answer: "Erosion", type: "multiple choice", choices: ["Weathering", "Erosion", "Deposition", "Compaction"] },
    { question: "Which of the following is an example of a consumer in an ecosystem?", answer: "Lion", type: "multiple choice", choices: ["Grass", "Tree", "Flower", "Lion"] },
    { question: "What is the measure of how hot or cold something is?", answer: "Temperature", type: "multiple choice", choices: ["Pressure", "Volume", "Temperature", "Mass"] },
    { question: "Which of the following is an example of a transparent material?", answer: "Glass", type: "multiple choice", choices: ["Wood", "Metal", "Plastic", "Glass"] },
    { question: "What is the process by which plants and animals release carbon dioxide?", answer: "Respiration", type: "multiple choice", choices: ["Photosynthesis", "Fermentation", "Respiration", "Decomposition"] },
    { question: "Which of the following is an example of a producer in an ecosystem?", answer: "Tree", type: "multiple choice", choices: ["Deer", "Rabbit", "Bird", "Tree"] },
    { question: "What is the process by which rocks and sediments are moved from one place to another?", answer: "Erosion", type: "multiple choice", choices: ["Weathering", "Deposition", "Erosion", "Compaction"] },
    { question: "What is the force that attracts objects towards each other?", answer: "Gravity", type: "multiple choice", choices: ["Magnetism", "Friction", "Gravity", "Inertia"] },
    { question: "Which of the following is an example of a nonrenewable resource?", answer: "Natural gas", type: "multiple choice", choices: ["Wind energy", "Solar energy", "Natural gas", "Hydroelectric power"] },
    { question: "What is the process by which a gas changes to a liquid?", answer: "Condensation", type: "multiple choice", choices: ["Evaporation", "Condensation", "Precipitation", "Transpiration"] },
    { question: "Which of the following is an example of a solution?", answer: "Saltwater", type: "multiple choice", choices: ["Oxygen", "Hydrogen", "Saltwater", "Gold"] },
    { question: "What is the layer of the Earth's atmosphere that contains the ozone layer?", answer: "Stratosphere", type: "multiple choice", choices: ["Troposphere", "Mesosphere", "Stratosphere", "Exosphere"] },
    { question: "What is the source of energy that powers the water cycle?", answer: "The Sun", type: "multiple choice", choices: ["The Moon", "The Sun", "The Earth's core", "Fossil fuels"] },
    { question: "Which of the following is an example of a physical change?", answer: "Breaking a glass", type: "multiple choice", choices: ["Burning wood", "Cooking an egg", "Breaking a glass", "Rusting metal"] },
    { question: "What is the process by which sediment is dropped off in a new location?", answer: "Deposition", type: "multiple choice", choices: ["Weathering", "Erosion", "Deposition", "Compaction"] },
    { question: "What is the layer of the Earth's atmosphere that contains the ozone layer?", answer: "Stratosphere", type: "multiple choice", choices: ["Troposphere", "Mesosphere", "Stratosphere", "Exosphere"] },
    { question: "Which of the following is an example of a producer in an ecosystem?", answer: "Grass", type: "multiple choice", choices: ["Lion", "Tiger", "Elephant", "Grass"] },
    { question: "Which of the following is a characteristic of a solid?", answer: "Definite shape and volume", type: "multiple choice", choices: ["Definite shape and volume", "Definite shape and indefinite volume", "Indefinite shape and definite volume", "Indefinite shape and volume"] },
    { question: "What is the process by which plants release water vapor through their leaves?", answer: "Transpiration", type: "multiple choice", choices: ["Evaporation", "Condensation", "Precipitation", "Transpiration"] },
    { question: "Which of the following is an example of a nonrenewable resource?", answer: "Coal", type: "multiple choice", choices: ["Wind energy", "Solar energy", "Coal", "Hydroelectric power"] },
    { question: "What is the force that opposes the motion of objects through air or water?", answer: "Drag", type: "multiple choice", choices: ["Gravity", "Magnetism", "Friction", "Drag"] },
    { question: "What is the process by which water changes from a liquid to a gas?", answer: "Evaporation", type: "multiple choice", choices: ["Condensation", "Precipitation", "Evaporation", "Transpiration"] },
    { question: "Which of the following is an example of a mixture?", answer: "Saltwater", type: "multiple choice", choices: ["Oxygen", "Hydrogen", "Saltwater", "Gold"] },
    { question: "What is the layer of the Earth's atmosphere where weather occurs?", answer: "Troposphere", type: "multiple choice", choices: ["Stratosphere", "Mesosphere", "Troposphere", "Thermosphere"] },
    { question: "What is the process by which sediment is carried away by wind or water?", answer: "Erosion", type: "multiple choice", choices: ["Weathering", "Erosion", "Deposition", "Compaction"] },
    { question: "Which of the following is an example of a consumer in an ecosystem?", answer: "Lion", type: "multiple choice", choices: ["Grass", "Tree", "Flower", "Lion"] },
    { question: "What is the measure of how hot or cold something is?", answer: "Temperature", type: "multiple choice", choices: ["Pressure", "Volume", "Temperature", "Mass"] },
    { question: "Which of the following is an example of a transparent material?", answer: "Glass", type: "multiple choice", choices: ["Wood", "Metal", "Plastic", "Glass"] },
    { question: "What is the process by which plants and animals release carbon dioxide?", answer: "Respiration", type: "multiple choice", choices: ["Photosynthesis", "Fermentation", "Respiration", "Decomposition"] }
]

const grade8_science = [
    { question: "Which of the following is an example of a renewable resource?", answer: "Solar energy", type: "multiple choice", choices: ["Coal", "Oil", "Solar energy", "Natural gas"] },
    { question: "What is the basic unit of life?", answer: "Cell", type: "multiple choice", choices: ["Atom", "Molecule", "Cell", "Tissue"] },
    { question: "Which of the following is a type of energy?", answer: "Electrical energy", type: "multiple choice", choices: ["Mass", "Volume", "Temperature", "Electrical energy"] },
    { question: "What is the process by which plants make their own food?", answer: "Photosynthesis", type: "multiple choice", choices: ["Respiration", "Digestion", "Photosynthesis", "Fermentation"] },
    { question: "Which of the following is an example of an inclined plane?", answer: "Ramp", type: "multiple choice", choices: ["Lever", "Pulley", "Wheel and axle", "Ramp"] },
    { question: "What is the force that attracts objects towards each other?", answer: "Gravity", type: "multiple choice", choices: ["Friction", "Magnetism", "Gravity", "Drag"] },
    { question: "Which of the following is an example of a conductor?", answer: "Copper", type: "multiple choice", choices: ["Plastic", "Wood", "Glass", "Copper"] },
    { question: "What is the process by which rocks are broken down into smaller pieces?", answer: "Weathering", type: "multiple choice", choices: ["Erosion", "Deposition", "Weathering", "Compaction"] },
    { question: "Which of the following is an example of a force?", answer: "Push", type: "multiple choice", choices: ["Heat", "Light", "Sound", "Push"] },
    { question: "What is the process by which a gas changes to a liquid?", answer: "Condensation", type: "multiple choice", choices: ["Evaporation", "Condensation", "Precipitation", "Transpiration"] },
    { question: "Which of the following is an example of a mixture?", answer: "Trail mix", type: "multiple choice", choices: ["Water", "Salt", "Sugar", "Trail mix"] },
    { question: "What is the unit of measurement for electric current?", answer: "Ampere", type: "multiple choice", choices: ["Volt", "Watt", "Ohm", "Ampere"] },
    { question: "Which of the following is an example of a mechanical wave?", answer: "Sound wave", type: "multiple choice", choices: ["Light wave", "Radio wave", "X-ray", "Sound wave"] },
    { question: "What is the process by which solid ice changes directly to water vapor?", answer: "Sublimation", type: "multiple choice", choices: ["Evaporation", "Condensation", "Sublimation", "Freezing"] },
    { question: "Which of the following is an example of an insulator?", answer: "Rubber", type: "multiple choice", choices: ["Aluminum", "Copper", "Iron", "Rubber"] },
    { question: "What is the process by which plants release water vapor through their leaves?", answer: "Transpiration", type: "multiple choice", choices: ["Evaporation", "Condensation", "Transpiration", "Precipitation"] },
    { question: "Which of the following is an example of a nonrenewable resource?", answer: "Coal", type: "multiple choice", choices: ["Wind", "Solar energy", "Water", "Coal"] },
    { question: "What is the process by which a liquid changes to a gas?", answer: "Evaporation", type: "multiple choice", choices: ["Melting", "Freezing", "Evaporation", "Condensation"] },
    { question: "Which of the following is an example of a chemical change?", answer: "Burning wood", type: "multiple choice", choices: ["Melting ice", "Cutting paper", "Stretching a rubber band", "Burning wood"] },
    { question: "What is the process by which an organism grows, develops, and repairs itself?", answer: "Cell division", type: "multiple choice", choices: ["Fertilization", "Cell division", "Photosynthesis", "Respiration"] },
    { question: "Which of the following is an example of a conductor?", answer: "Silver", type: "multiple choice", choices: ["Plastic", "Glass", "Wood", "Silver"] },
    { question: "What is the process by which water vapor changes to liquid water?", answer: "Condensation", type: "multiple choice", choices: ["Evaporation", "Sublimation", "Condensation", "Freezing"] },
    { question: "Which of the following is an example of a mixture?", answer: "Air", type: "multiple choice", choices: ["Gold", "Salt", "Sugar", "Air"] },
    { question: "What is the unit of measurement for distance?", answer: "Meter", type: "multiple choice", choices: ["Gram", "Liter", "Second", "Meter"] },
    { question: "Which of the following is an example of a mechanical advantage?", answer: "Lever", type: "multiple choice", choices: ["Wheel and axle", "Pulley", "Inclined plane", "Lever"] },
    { question: "What is the process by which plants take in carbon dioxide and release oxygen?", answer: "Photosynthesis", type: "multiple choice", choices: ["Respiration", "Fermentation", "Photosynthesis", "Digestion"] },
    { question: "Which of the following is an example of a reflection of light?", answer: "Mirror", type: "multiple choice", choices: ["Lens", "Prism", "Filter", "Mirror"] },
    { question: "What is the process by which sediment is dropped or left behind?", answer: "Deposition", type: "multiple choice", choices: ["Erosion", "Weathering", "Deposition", "Compaction"] },
    { question: "Which of the following is an example of a nonrenewable resource?", answer: "Oil", type: "multiple choice", choices: ["Wind", "Solar energy", "Water", "Oil"] },
    { question: "What is the process by which an object moves in a circular path?", answer: "Centripetal motion", type: "multiple choice", choices: ["Linear motion", "Rotational motion", "Centripetal motion", "Random motion"] },
    { question: "Which of the following is an example of a chemical change?", answer: "Baking a cake", type: "multiple choice", choices: ["Melting ice", "Tearing paper", "Mixing salt and water", "Baking a cake"] },
    { question: "What is the process by which water changes from a liquid to a solid?", answer: "Freezing", type: "multiple choice", choices: ["Melting", "Condensation", "Freezing", "Vaporization"] },
    { question: "Which of the following is an example of an insulator?", answer: "Wood", type: "multiple choice", choices: ["Copper", "Silver", "Aluminum", "Wood"] },
    { question: "What is the process by which a solid changes directly to a gas without becoming a liquid first?", answer: "Sublimation", type: "multiple choice", choices: ["Evaporation", "Condensation", "Sublimation", "Deposition"] },
    { question: "Which of the following is an example of a producer?", answer: "Grass", type: "multiple choice", choices: ["Lion", "Tiger", "Elephant", "Grass"] },
    { question: "What is the unit of measurement for time?", answer: "Second", type: "multiple choice", choices: ["Meter", "Gram", "Liter", "Second"] },
    { question: "Which of the following is an example of a simple machine?", answer: "Wheel and axle", type: "multiple choice", choices: ["Battery", "Motor", "Circuit", "Wheel and axle"] },
    { question: "What is the process by which plants and animals break down food to release energy?", answer: "Respiration", type: "multiple choice", choices: ["Photosynthesis", "Fermentation", "Respiration", "Digestion"] },
    { question: "Which of the following is an example of a refraction of light?", answer: "Bending of light when passing through a glass prism", type: "multiple choice", choices: ["Reflection of light in a mirror", "Scattering of light by a rough surface", "Absorption of light by a black object", "Bending of light when passing through a glass prism"] },
    { question: "What is the process by which a gas changes to a liquid?", answer: "Condensation", type: "multiple choice", choices: ["Evaporation", "Sublimation", "Condensation", "Vaporization"] },
    { question: "Which of the following is an example of a sedimentary rock?", answer: "Sandstone", type: "multiple choice", choices: ["Granite", "Marble", "Basalt", "Sandstone"] },
    { question: "What is the process by which energy is transferred by the movement of fluids?", answer: "Convection", type: "multiple choice", choices: ["Conduction", "Radiation", "Evaporation", "Convection"] },
    { question: "Which of the following is an example of a decomposer?", answer: "Fungi", type: "multiple choice", choices: ["Grasshopper", "Butterfly", "Bird", "Fungi"] },
    { question: "What is the process by which rock fragments are carried away by wind, water, or ice?", answer: "Erosion", type: "multiple choice", choices: ["Weathering", "Deposition", "Erosion", "Compaction"] },
    { question: "Which of the following is an example of a renewable resource?", answer: "Wind energy", type: "multiple choice", choices: ["Coal", "Oil", "Natural gas", "Wind energy"] },
    { question: "What is the process by which an object floats or rises in a fluid?", answer: "Buoyancy", type: "multiple choice", choices: ["Inertia", "Friction", "Magnetism", "Buoyancy"] },
    { question: "Which of the following is an example of a fossil fuel?", answer: "Natural gas", type: "multiple choice", choices: ["Solar energy", "Wind energy", "Geothermal energy", "Natural gas"] },
    { question: "What is the process by which rocks are packed and squeezed together?", answer: "Compaction", type: "multiple choice", choices: ["Deposition", "Erosion", "Weathering", "Compaction"] },
    { question: "Which of the following is an example of a sound wave?", answer: "Music", type: "multiple choice", choices: ["Heat", "Light", "Electricity", "Music"] },
    { question: "What is the process by which an organism produces offspring?", answer: "Reproduction", type: "multiple choice", choices: ["Growth", "Metabolism", "Respiration", "Reproduction"] },
]

exports = module.exports
exports.grade6_science = grade6_science
exports.grade7_science = grade7_science
exports.grade8_science = grade8_science
exports.biology = biology
exports.AP_biology = AP_biology
exports.chemistry = chemistry
exports.AP_chemistry = AP_chemistry
exports.physics = physics
exports.AP_physics = AP_physics